package interfaz;

import codigoNegocio.Estadisticas;
import codigoNegocio.Jugador;
import codigoNegocio.JugadorConcreto;
import codigoNegocio.Mediador;
import codigoNegocio.MediadorConcreto;
import codigoNegocio.Servidor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * Registro: Ventana encargada del Registro.
 * 
 * @author Alberto Fernández Hernández
 * @author Francisco Cano Díaz
 */
public class Registro extends javax.swing.JFrame {

    // Mediador encargado de la comunicación entre jugadores.
    private Mediador mediador;
    // Proxy encargado de la comunicación entre el cliente y el Servidor.
    private Servidor proxy;
    // Ventana Principal anterior a esta ventana.
    private JFrame ventanaPrincipal;
    
    /**
     * Constructor.
     * 
     * @param ventanaPrincipal Ventana Principal anterior a esta ventana.
     * @param proxy Proxy encargado de la comunicación entre el cliente y el Servidor.
     */
    public Registro(JFrame ventanaPrincipal, Servidor proxy) {
        this.ventanaPrincipal = ventanaPrincipal;
        this.proxy = proxy;
        this.mediador = new MediadorConcreto();
        // Iniciamos la ventana, establecemos sus dimensiones y la centramos.
        initComponents();
        centrarVentana(this);
        this.setSize(470, 360);
    }
    
    /**
     * Método encargado de centrar la ventana en función de la resolución de
     * pantalla actual.
     * 
     * @param frame Ventana actual.
     */
    public void centrarVentana(Window frame) {
        // Obtenemos la dimensión de la pantalla.
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        // Obtenemos las dimensiones para centrar la ventana.
        int anchura = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
        int altura = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
        // Establecemos las dimensiones.
        frame.setLocation(anchura, altura);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nombreTF = new javax.swing.JTextField();
        apellidosTF = new javax.swing.JTextField();
        edadTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        usuarioTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        aceptarButton = new javax.swing.JButton();
        passwordTF = new javax.swing.JPasswordField();
        volverButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BATTLEVA: REGISTRO");
        setMaximumSize(new java.awt.Dimension(470, 360));
        setMinimumSize(new java.awt.Dimension(470, 360));
        setPreferredSize(new java.awt.Dimension(470, 360));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Copperplate", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BIENVENIDO A BATTLEVA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 30, 250, 30);

        jLabel3.setFont(new java.awt.Font("Copperplate", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("REGISTRO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 70, 80, 16);

        jLabel4.setFont(new java.awt.Font("Copperplate", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NOMBRE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 114, 70, 19);

        jLabel5.setFont(new java.awt.Font("Copperplate", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("APELLIDOS");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(85, 144, 80, 19);

        jLabel6.setFont(new java.awt.Font("Copperplate", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("EDAD");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 174, 50, 19);

        nombreTF.setMaximumSize(new java.awt.Dimension(190, 25));
        nombreTF.setMinimumSize(new java.awt.Dimension(190, 25));
        nombreTF.setPreferredSize(new java.awt.Dimension(190, 25));
        getContentPane().add(nombreTF);
        nombreTF.setBounds(170, 110, 190, 25);

        apellidosTF.setMaximumSize(new java.awt.Dimension(190, 25));
        apellidosTF.setMinimumSize(new java.awt.Dimension(190, 25));
        apellidosTF.setPreferredSize(new java.awt.Dimension(190, 25));
        getContentPane().add(apellidosTF);
        apellidosTF.setBounds(170, 140, 190, 25);

        edadTF.setMaximumSize(new java.awt.Dimension(190, 25));
        edadTF.setMinimumSize(new java.awt.Dimension(190, 25));
        edadTF.setPreferredSize(new java.awt.Dimension(190, 25));
        getContentPane().add(edadTF);
        edadTF.setBounds(170, 170, 190, 25);

        jLabel7.setFont(new java.awt.Font("Copperplate", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("USUARIO");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(85, 223, 70, 20);

        usuarioTF.setMaximumSize(new java.awt.Dimension(190, 25));
        usuarioTF.setMinimumSize(new java.awt.Dimension(190, 25));
        usuarioTF.setPreferredSize(new java.awt.Dimension(190, 25));
        getContentPane().add(usuarioTF);
        usuarioTF.setBounds(170, 220, 190, 25);

        jLabel8.setFont(new java.awt.Font("Copperplate", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CONTRASEÑA");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(65, 252, 110, 20);

        aceptarButton.setText("ACEPTAR");
        aceptarButton.setFocusable(false);
        aceptarButton.setMaximumSize(new java.awt.Dimension(95, 23));
        aceptarButton.setMinimumSize(new java.awt.Dimension(95, 23));
        aceptarButton.setPreferredSize(new java.awt.Dimension(95, 23));
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(aceptarButton);
        aceptarButton.setBounds(265, 300, 95, 23);

        passwordTF.setMaximumSize(new java.awt.Dimension(190, 25));
        passwordTF.setMinimumSize(new java.awt.Dimension(190, 25));
        passwordTF.setPreferredSize(new java.awt.Dimension(190, 25));
        getContentPane().add(passwordTF);
        passwordTF.setBounds(170, 250, 190, 25);

        volverButton.setText("VOLVER");
        volverButton.setFocusable(false);
        volverButton.setMaximumSize(new java.awt.Dimension(85, 23));
        volverButton.setMinimumSize(new java.awt.Dimension(85, 23));
        volverButton.setPreferredSize(new java.awt.Dimension(85, 23));
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });
        getContentPane().add(volverButton);
        volverButton.setBounds(170, 300, 85, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/portada.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 473, 338);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Método encargado de cerrar la ventana actual e iniciar la Ventana
     * Principal al pulsar el botón Volver.
     * 
     * @param evt Evento del botón Volver.
     */
    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonActionPerformed
        this.dispose();
        ventanaPrincipal.setVisible(true);
    }//GEN-LAST:event_volverButtonActionPerformed

    /**
     * Método encargado de registar al nuevo Jugador e iniciar la Ventana
     * de Selección al pulsar el botón Aceptar llamando a los métodos correspondientes.
     * 
     * @param evt Evento del botón Aceptar.
     */
    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        try{
            // Creamos un nuevo objeto Estadisticas y Jugador con los campos
            // introducidos en la ventana actual.
            Estadisticas estadisticas = new Estadisticas();
            Jugador jugador = new JugadorConcreto(nombreTF.getText(), apellidosTF.getText(),
                    Integer.parseInt(edadTF.getText()), usuarioTF.getText(),
                                     passwordTF.getText(), mediador, estadisticas);
            
            // Si el Jugador es nuevo en el sistema, lo incluimos.
            if(proxy.addJugador(jugador)) {
                JOptionPane.showMessageDialog(this, "Jugador registrado con éxito", "Informacion",
                                              JOptionPane.INFORMATION_MESSAGE);
                // Creamos la Ventana de Selección.
                VentanaSeleccion ventanaSeleccion = new VentanaSeleccion(proxy, jugador);
                // Cerramos la ventana actual...
                this.dispose();
                // E iniciamos la Ventana de Selección.
                ventanaSeleccion.setVisible(true);
            } else { // En caso de ya estar el Jugador en el sistema.
                JOptionPane.showMessageDialog(this, "Jugador ya existente", "Error",
                                              JOptionPane.ERROR_MESSAGE);
            }
            // Vaciamos los campos.
            usuarioTF.setText("");
            passwordTF.setText("");
        } catch(NumberFormatException e){
            // En caso de que la edad introducida no sea un número.
            JOptionPane.showMessageDialog(this, "La edad no es valida", "Error" ,
                                          JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_aceptarButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JTextField apellidosTF;
    private javax.swing.JTextField edadTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nombreTF;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JTextField usuarioTF;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables
}