package interfaz;

import codigoNegocio.Proxy;
import codigoNegocio.Servidor;
import codigoNegocio.ServidorCentral;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import java.io.*;

/**
 * VentanaPrincipal: Ventana Principal de la aplicación encargada de dirigirnos
 *                   a la Ventana de Iniciar Sesión o a la de Registro.
 * 
 * @author Alberto Fernández Hernández
 * @author Francisco Cano Díaz
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    // Proxy encargado de la comunicación entre el cliente y el Servidor.
    Servidor proxy;
    
    /**
     * Constructor.
     * 
     */
    public VentanaPrincipal() {
        // Restauramos el Servidor en caso de haber sido guardado.
        this.proxy = new Proxy(restaurarServidor());
        // Iniciamos la ventana, establecemos sus dimensiones y la centramos.
        initComponents();
        this.setSize(470, 330);
        centrarVentana(this);
    }
    
    /**
     * Método encargado de centrar la ventana en función de la resolución de
     * pantalla actual.
     * 
     * @param frame Ventana actual.
     */
    public void centrarVentana(Window frame) {
        // Obtenemos la dimensión de la pantalla.
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        // Obtenemos las dimensiones para centrar la ventana.
        int anchura = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
        int altura = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
        // Establecemos las dimensiones.
        frame.setLocation(anchura, altura);
    }
    
    /**
     * Método encargado de restaurar el Servidor en caso de haber hecho previamente
     * un backup del mismo.
     * 
     * @return Servidor restaurado.
     */
    public Servidor restaurarServidor() {
        ServidorCentral sc = null;
        try {
            File sistema = new File("serverData.dat");
            if(sistema.exists()) { // Si existe el backup.
                // Leemos el fichero y almacenamos el objeto Servidor.
                FileInputStream f = new FileInputStream(sistema);
                ObjectInputStream o = new ObjectInputStream(f);
                sc = (ServidorCentral) o.readObject();
                o.close();
                f.close();
            }
            else { // En caso de no existir, creamos uno nuevo.
                sc = new ServidorCentral("Servidor central");
                // Realizamos un backup del nuevo Servidor.
                sc.backupServidor();
            }
        } catch (IOException | ClassNotFoundException ex) {
            ex.printStackTrace();
        }
        return sc;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        iniciarSesionButton = new javax.swing.JButton();
        registroButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BATTLEVA");
        setMaximumSize(new java.awt.Dimension(470, 330));
        setMinimumSize(new java.awt.Dimension(470, 330));
        setPreferredSize(new java.awt.Dimension(470, 330));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Copperplate", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BIENVENIDO A BATTLEVA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 90, 250, 20);

        iniciarSesionButton.setFont(new java.awt.Font("Copperplate", 1, 13)); // NOI18N
        iniciarSesionButton.setText("INICIAR SESION");
        iniciarSesionButton.setFocusable(false);
        iniciarSesionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSesionButtonActionPerformed(evt);
            }
        });
        getContentPane().add(iniciarSesionButton);
        iniciarSesionButton.setBounds(155, 130, 150, 30);

        registroButton.setFont(new java.awt.Font("Copperplate", 1, 13)); // NOI18N
        registroButton.setText("REGISTRARSE");
        registroButton.setFocusable(false);
        registroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroButtonActionPerformed(evt);
            }
        });
        getContentPane().add(registroButton);
        registroButton.setBounds(155, 180, 150, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/portada.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(470, 330));
        jLabel1.setMinimumSize(new java.awt.Dimension(470, 330));
        jLabel1.setPreferredSize(new java.awt.Dimension(470, 330));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 470, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método encargado de redirigirnos a la Ventana de Iniciar Sesión al pulsar
     * el botón de Iniciar Sesión.
     * 
     * @param evt Evento del botón Iniciar Sesión.
     */
    private void iniciarSesionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSesionButtonActionPerformed
        IniciarSesion iniciarSesion = new IniciarSesion(this, proxy);
        iniciarSesion.setLocationRelativeTo(this);
        iniciarSesion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_iniciarSesionButtonActionPerformed

    /**
     * Método encargado de redirigirnos a la Ventana de Registro al pulsar
     * el botón de Registrarse.
     * 
     * @param evt Evento del botón Registrarse.
     */
    private void registroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroButtonActionPerformed
        Registro registro = new Registro(this, proxy);
        registro.setLocationRelativeTo(this);
        registro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registroButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton iniciarSesionButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton registroButton;
    // End of variables declaration//GEN-END:variables
}