package interfaz;

import codigoNegocio.Jugador;
import codigoNegocio.Servidor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import javax.swing.JFrame;

/**
 * VentanaEstadisticas: Ventana encargada de mostrar las estadísticas del Juagdor.
 * 
 * @author Alberto Fernández Hernández
 * @author Francisco Cano Díaz
 */
public class VentanaEstadisticas extends javax.swing.JFrame {

    // Proxy encargado de la comunicación entre el cliente y el Servidor.
    private Servidor proxy;
    // Jugador al que pertenecen dichas estadísticas.
    private Jugador jugador;
    // Ventana Selección anterior a esta ventana.
    private JFrame ventanaSeleccion;
    
    /**
     * Constructor.
     * 
     * @param proxy Proxy encargado de la comunicación entre el cliente y el Servidor.
     * @param jugador Jugador al que pertenecen dichas estadísticas.
     * @param ventanaSeleccion Ventana Selección anterior a esta ventana.
     */
    public VentanaEstadisticas(Servidor proxy, Jugador jugador, JFrame ventanaSeleccion) {
        this.proxy = proxy;
        this.jugador = jugador;
        this.ventanaSeleccion = ventanaSeleccion;
        // Iniciamos la ventana, establecemos sus dimensiones y la centramos.
        initComponents();
        this.setSize(770, 460);
        centrarVentana(this);
        // Iniciamos las estadísticas con lo almacenado en el Jugador.
        iniciarEstadisticas();
    }
    
    /**
     * Método encargado de centrar la ventana en función de la resolución de
     * pantalla actual.
     * 
     * @param frame Ventana actual.
     */
    public void centrarVentana(Window frame) {
        // Obtenemos la dimensión de la pantalla.
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        // Obtenemos las dimensiones para centrar la ventana.
        int anchura = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
        int altura = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
        // Establecemos las dimensiones.
        frame.setLocation(anchura, altura);
    }
    
    /**
     * Método encargado de cargar las estadísticas guardadas en el Jugador.
     * 
     */
    public void iniciarEstadisticas(){
        victoriasTF.setText(Integer.toString
                           (proxy.getJugador
                           (jugador.getUsuario()).getEstadisticas().getNumeroDeVictorias()));
        derrotasTF.setText(Integer.toString
                          (proxy.getJugador
                          (jugador.getUsuario()).getEstadisticas().getNumeroDeDerrotas()));
        totalBarcosHundidosTF.setText(Integer.toString
                                     (proxy.getJugador
                                     (jugador.getUsuario()).getEstadisticas().getTotalBarcosHundidos()));
        fragataTF.setText(Integer.toString
                         (proxy.getJugador
                         (jugador.getUsuario()).getEstadisticas().getTotalBarcosHundidosPorCategorias().get(0)));
        destructorTF.setText(Integer.toString
                            (proxy.getJugador
                            (jugador.getUsuario()).getEstadisticas().getTotalBarcosHundidosPorCategorias().get(1)));
        acorazadoTF.setText(Integer.toString
                           (proxy.getJugador
                           (jugador.getUsuario()).getEstadisticas().getTotalBarcosHundidosPorCategorias().get(2)));
        portaavionesTF.setText(Integer.toString
                           (proxy.getJugador
                           (jugador.getUsuario()).getEstadisticas().getTotalBarcosHundidosPorCategorias().get(3)));
        submarinoTF.setText(Integer.toString
                           (proxy.getJugador
                           (jugador.getUsuario()).getEstadisticas().getTotalBarcosHundidosPorCategorias().get(4)));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        victoriasTF = new javax.swing.JTextField();
        derrotasTF = new javax.swing.JTextField();
        totalBarcosHundidosTF = new javax.swing.JTextField();
        volverButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fragataTF = new javax.swing.JTextField();
        destructorTF = new javax.swing.JTextField();
        acorazadoTF = new javax.swing.JTextField();
        portaavionesTF = new javax.swing.JTextField();
        submarinoTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BATTLEVA: ESTADÍSTICAS");
        setMaximumSize(new java.awt.Dimension(770, 460));
        setMinimumSize(new java.awt.Dimension(770, 460));
        setPreferredSize(new java.awt.Dimension(770, 460));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Copperplate", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ESTADISTICAS DEL JUGADOR");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(118, 40, 533, 47);

        jLabel3.setFont(new java.awt.Font("Copperplate", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TOTAL VICTORIAS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(118, 110, 164, 24);

        jLabel4.setFont(new java.awt.Font("Copperplate", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TOTAL DERROTAS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(118, 160, 166, 24);

        jLabel5.setFont(new java.awt.Font("Copperplate", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TOTAL BARCOS HUNDIDOS");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 210, 244, 24);

        victoriasTF.setEditable(false);
        victoriasTF.setFocusable(false);
        victoriasTF.setMaximumSize(new java.awt.Dimension(50, 30));
        victoriasTF.setMinimumSize(new java.awt.Dimension(50, 30));
        victoriasTF.setPreferredSize(new java.awt.Dimension(50, 30));
        getContentPane().add(victoriasTF);
        victoriasTF.setBounds(292, 105, 50, 30);

        derrotasTF.setEditable(false);
        derrotasTF.setFocusable(false);
        derrotasTF.setMaximumSize(new java.awt.Dimension(50, 30));
        derrotasTF.setMinimumSize(new java.awt.Dimension(50, 30));
        derrotasTF.setPreferredSize(new java.awt.Dimension(50, 30));
        getContentPane().add(derrotasTF);
        derrotasTF.setBounds(292, 155, 50, 30);

        totalBarcosHundidosTF.setEditable(false);
        totalBarcosHundidosTF.setFocusable(false);
        totalBarcosHundidosTF.setMaximumSize(new java.awt.Dimension(50, 30));
        totalBarcosHundidosTF.setMinimumSize(new java.awt.Dimension(50, 30));
        totalBarcosHundidosTF.setPreferredSize(new java.awt.Dimension(50, 30));
        getContentPane().add(totalBarcosHundidosTF);
        totalBarcosHundidosTF.setBounds(292, 205, 50, 30);

        volverButton.setText("VOLVER");
        volverButton.setFocusable(false);
        volverButton.setMaximumSize(new java.awt.Dimension(85, 23));
        volverButton.setMinimumSize(new java.awt.Dimension(85, 23));
        volverButton.setPreferredSize(new java.awt.Dimension(85, 23));
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });
        getContentPane().add(volverButton);
        volverButton.setBounds(20, 380, 85, 23);

        jLabel6.setFont(new java.awt.Font("Copperplate", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TOTAL BARCOS HUNDIDOS POR CLASES");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(423, 90, 277, 19);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/fragataRecortada.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(420, 210, 220, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/destructorRecortada.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(430, 160, 230, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/acorazadoRecortada.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(490, 120, 150, 28);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/portaavionesRecortada.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(350, 260, 290, 100);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/submarinoRecortada.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(440, 380, 200, 30);

        fragataTF.setEditable(false);
        fragataTF.setFocusable(false);
        fragataTF.setMaximumSize(new java.awt.Dimension(50, 30));
        fragataTF.setMinimumSize(new java.awt.Dimension(50, 30));
        fragataTF.setPreferredSize(new java.awt.Dimension(50, 30));
        getContentPane().add(fragataTF);
        fragataTF.setBounds(650, 120, 50, 30);

        destructorTF.setEditable(false);
        destructorTF.setFocusable(false);
        destructorTF.setMaximumSize(new java.awt.Dimension(50, 30));
        destructorTF.setMinimumSize(new java.awt.Dimension(50, 30));
        destructorTF.setPreferredSize(new java.awt.Dimension(50, 30));
        getContentPane().add(destructorTF);
        destructorTF.setBounds(650, 166, 50, 30);

        acorazadoTF.setEditable(false);
        acorazadoTF.setFocusable(false);
        acorazadoTF.setMaximumSize(new java.awt.Dimension(50, 30));
        acorazadoTF.setMinimumSize(new java.awt.Dimension(50, 30));
        acorazadoTF.setPreferredSize(new java.awt.Dimension(50, 30));
        getContentPane().add(acorazadoTF);
        acorazadoTF.setBounds(650, 210, 50, 30);

        portaavionesTF.setEditable(false);
        portaavionesTF.setFocusable(false);
        portaavionesTF.setMaximumSize(new java.awt.Dimension(50, 30));
        portaavionesTF.setMinimumSize(new java.awt.Dimension(50, 30));
        portaavionesTF.setPreferredSize(new java.awt.Dimension(50, 30));
        getContentPane().add(portaavionesTF);
        portaavionesTF.setBounds(650, 296, 50, 30);

        submarinoTF.setEditable(false);
        submarinoTF.setFocusable(false);
        submarinoTF.setMaximumSize(new java.awt.Dimension(50, 30));
        submarinoTF.setMinimumSize(new java.awt.Dimension(50, 30));
        submarinoTF.setPreferredSize(new java.awt.Dimension(50, 30));
        getContentPane().add(submarinoTF);
        submarinoTF.setBounds(650, 380, 50, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/PortadaGrande.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-580, -280, 1400, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método encargado de cerrar la ventana actual e iniciar la Ventana
     * Selección al pulsar el botón Volver.
     * 
     * @param evt Evento del botón Volver.
     */
    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonActionPerformed
        this.dispose();
        ventanaSeleccion.setVisible(true);
    }//GEN-LAST:event_volverButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acorazadoTF;
    private javax.swing.JTextField derrotasTF;
    private javax.swing.JTextField destructorTF;
    private javax.swing.JTextField fragataTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField portaavionesTF;
    private javax.swing.JTextField submarinoTF;
    private javax.swing.JTextField totalBarcosHundidosTF;
    private javax.swing.JTextField victoriasTF;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables
}